Name: product.rpc
ListenOn: 127.0.0.1:33006
Etcd:
  Hosts:
  - 127.0.0.1:2379
  Key: product.rpc
Mysql:
  DataSource: air:@tcp(localhost)/air?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai
CacheRedis:
  - Host: localhost:6379
    Pass: 
    Type: node